Ligne numero = 2 , mot non trouvé = 'x'
Ligne numero = 3 , mot non trouvé = 'str'
Ligne numero = 4 , mot non trouvé = 'x'
Ligne numero = 5 , mot non trouvé = 'x'
Ligne numero = 5 , mot non trouvé = '>'
Ligne numero = 5 , mot non trouvé = '0'
Ligne numero = 6 , mot non trouvé = '<<'
Ligne numero = 6 , mot non trouvé = 'La'
Ligne numero = 6 , mot non trouvé = 'valeur'
Ligne numero = 6 , mot non trouvé = 'est'
Ligne numero = 6 , mot non trouvé = 'positive'
Ligne numero = 6 , mot non trouvé = '>> ) ;'
Ligne numero = 7 , mot non trouvé = 'Fin Si'
Ligne numero = 2 , mot non trouvé = 'x'
Ligne numero = 3 , mot non trouvé = 'str'
Ligne numero = 4 , mot non trouvé = 'x'
Ligne numero = 5 , mot non trouvé = 'x'
Ligne numero = 5 , mot non trouvé = '>'
Ligne numero = 5 , mot non trouvé = '0'
Ligne numero = 6 , mot non trouvé = '<<'
Ligne numero = 6 , mot non trouvé = 'La'
Ligne numero = 6 , mot non trouvé = 'valeur'
Ligne numero = 6 , mot non trouvé = 'est'
Ligne numero = 6 , mot non trouvé = 'positive'
Ligne numero = 6 , mot non trouvé = '>> ) ;'
Ligne numero = 7 , mot non trouvé = 'Fin Si'
